/* automatically generated by rust-bindgen 0.60.1 */

pub type size_t = ::std::os::raw::c_ulonglong;
pub type wchar_t = ::std::os::raw::c_ushort;
pub type max_align_t = f64;
extern "C" {
    pub fn w_lz4_compress_bound(p_input_size: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn w_lz4_compress_default(
        p_src: *const ::std::os::raw::c_char,
        p_dst: *mut ::std::os::raw::c_char,
        p_src_size: ::std::os::raw::c_int,
        p_dst_size: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn w_lz4_compress_fast(
        p_source: *const ::std::os::raw::c_char,
        p_dst: *mut ::std::os::raw::c_char,
        p_src_size: ::std::os::raw::c_int,
        p_dst_size: ::std::os::raw::c_int,
        p_acceleration: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn w_lz4_decompress_safe(
        p_src: *const ::std::os::raw::c_char,
        p_dst: *mut ::std::os::raw::c_char,
        p_src_size: ::std::os::raw::c_int,
        p_dst_size: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
