/* automatically generated by rust-bindgen 0.60.1 */

pub const W_MAX_PATH: u32 = 260;
pub type size_t = ::std::os::raw::c_ulonglong;
pub type wchar_t = ::std::os::raw::c_ushort;
pub type max_align_t = f64;
pub type int_least64_t = i64;
pub type uint_least64_t = u64;
pub type int_fast64_t = i64;
pub type uint_fast64_t = u64;
pub type int_least32_t = i32;
pub type uint_least32_t = u32;
pub type int_fast32_t = i32;
pub type uint_fast32_t = u32;
pub type int_least16_t = i16;
pub type uint_least16_t = u16;
pub type int_fast16_t = i16;
pub type uint_fast16_t = u16;
pub type int_least8_t = i8;
pub type uint_least8_t = u8;
pub type int_fast8_t = i8;
pub type uint_fast8_t = u8;
pub type intmax_t = ::std::os::raw::c_longlong;
pub type uintmax_t = ::std::os::raw::c_ulonglong;
extern "C" {
    pub fn w_lz4_compress_bound(p_input_size: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn w_lz4_compress_default(
        p_src: *const ::std::os::raw::c_char,
        p_dst: *mut ::std::os::raw::c_char,
        p_src_size: ::std::os::raw::c_int,
        p_dst_size: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn w_lz4_compress_fast(
        p_source: *const ::std::os::raw::c_char,
        p_dst: *mut ::std::os::raw::c_char,
        p_src_size: ::std::os::raw::c_int,
        p_dst_size: ::std::os::raw::c_int,
        p_acceleration: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn w_lz4_decompress_safe(
        p_src: *const ::std::os::raw::c_char,
        p_dst: *mut ::std::os::raw::c_char,
        p_src_size: ::std::os::raw::c_int,
        p_dst_size: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
