/* automatically generated by rust-bindgen 0.60.1 */

pub const W_MAX_PATH: u32 = 260;
pub type size_t = ::std::os::raw::c_ulonglong;
pub type wchar_t = ::std::os::raw::c_ushort;
pub type max_align_t = f64;
pub type int_least64_t = i64;
pub type uint_least64_t = u64;
pub type int_fast64_t = i64;
pub type uint_fast64_t = u64;
pub type int_least32_t = i32;
pub type uint_least32_t = u32;
pub type int_fast32_t = i32;
pub type uint_fast32_t = u32;
pub type int_least16_t = i16;
pub type uint_least16_t = u16;
pub type int_fast16_t = i16;
pub type uint_fast16_t = u16;
pub type int_least8_t = i8;
pub type uint_least8_t = u8;
pub type int_fast8_t = i8;
pub type uint_fast8_t = u8;
pub type intmax_t = ::std::os::raw::c_longlong;
pub type uintmax_t = ::std::os::raw::c_ulonglong;
extern "C" {
    #[doc = " returns wolf version"]
    #[doc = " @param p_buf buffer with maximum size of 260 characters"]
    #[doc = " @param p_len the length of buffer, maximum size is 260"]
    #[doc = " @return string format with the following style"]
    #[doc = " \"<major>.<minor>.<patch>.<debug>\""]
    pub fn w_sys_version(p_buf: *mut ::std::os::raw::c_char, p_len: size_t);
}
