/* automatically generated by rust-bindgen 0.60.1 */

pub type size_t = ::std::os::raw::c_ulonglong;
pub type wchar_t = ::std::os::raw::c_ushort;
pub type max_align_t = f64;
extern "C" {
    #[doc = " returns wolf version"]
    #[doc = " @return string format with the following style"]
    #[doc = " \"<major>.<minor>.<patch>.<debug>\""]
    pub fn w_sys_version(p_buf: *mut ::std::os::raw::c_char, p_len: size_t);
}
