// Automatically generated by Interoptopus.

#ifndef _WOLF_H_
#define _WOLF_H_

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>




typedef enum ffierror
    {
    FFIERROR_OK = 0,
    } ffierror;

typedef struct w_string
    {
    uint8_t* data;
    uint64_t len;
    } w_string;


/// Returns the version of this API.
uint32_t wolf_version();

/// Returns the version of this API.
ffierror wolf_string(w_string* p_arg);


#ifdef __cplusplus
}
#endif

#endif /* _WOLF_H_ */
