/*
    Project			 : Wolf Engine. Copyright(c) Pooya Eimandar (http://PooyaEimandar.com) . All rights reserved.
    Source			 : Please direct any bug to https://github.com/PooyaEimandar/Wolf.Engine/issues
    Website			 : http://WolfSource.io
    Name			 : py_color.h
    Description		 : The python exporter for w_color class
    Comment          :
*/

#ifdef __PYTHON__

#if _MSC_VER > 1000
#pragma once
#endif

#ifndef __PY_COLOR_H__
#define __PY_COLOR_H__

namespace pywolf
{
    static void py_color_export()
    {
        using namespace boost::python;
        using namespace wolf::system;
        
        //export w_bounding_box class
        class_<w_color>("w_color", init<>())
            .def_readwrite("r", &w_color::r, "Red channel(0-255)")
            .def_readwrite("g", &w_color::g, "Green channel(0-255)")
            .def_readwrite("b", &w_color::b, "Blue channel(0-255)")
            .def_readwrite("a", &w_color::a, "Alpha channel(0-255)")
            .def("from_string", &w_color::py_from_string, "Create w_color from string in the format of \"r(0 - 255), g(0 - 255), b(0 - 255), a(0 - 255)\", for example \"255, 0, 0, 255\"")
            .def("from_hex", &w_color::py_from_hex, "Convert HEX color to w_color")
            .def("to_hex", &w_color::py_to_hex, "Convert RGBA to HEX")
            .def("to_color", &w_color::py_to_color, "Convert array of float(elements have value between 0.0f and 1.0f) to w_color")
            .def("ALICE_BLUE", &w_color::py_ALICE_BLUE, "ALICE_BLUE")
            .def("ANTIQUE_WHITE", &w_color::py_ANTIQUE_WHITE, "ANTIQUE_WHITE")
            .def("AQUA", &w_color::py_AQUA, "AQUA")
            .def("AQUAMARINE", &w_color::py_AQUAMARINE, "AQUAMARINE")
            .def("AZURE", &w_color::py_AZURE, "AZURE")
            .def("BEIGE", &w_color::py_BEIGE, "BEIGE")
            .def("BISQUE", &w_color::py_BISQUE, "BISQUE")
            .def("BLACK", &w_color::py_BLACK, "BLACK")
            .def("BLANCHED_ALMOND", &w_color::py_BLANCHED_ALMOND, "BLANCHED_ALMOND")
            .def("BLUE", &w_color::py_BLUE, "BLUE")
            .def("BLUE_VIOLET", &w_color::py_BLUE_VIOLET, "BLUE_VIOLET")
            .def("BROWN", &w_color::py_BROWN, "BROWN")
            .def("BURLY_WOOD", &w_color::py_BURLY_WOOD, "BURLY_WOOD")
            .def("CADET_BLUE", &w_color::py_CADET_BLUE, "CADET_BLUE")
            .def("CHARTREUSE", &w_color::py_CHARTREUSE, "CHARTREUSE")
            .def("CHOCOLATE", &w_color::py_CHOCOLATE, "CHOCOLATE")
            .def("CORAL", &w_color::py_CORAL, "CORAL")
            .def("CORNFLOWER_BLUE", &w_color::py_CORNFLOWER_BLUE, "CORNFLOWER_BLUE")
            .def("CORNSILK", &w_color::py_CORNSILK, "CORNSILK")
            .def("CRIMSON", &w_color::py_CRIMSON, "CRIMSON")
            .def("CYAN", &w_color::py_CYAN, "CYAN")
            .def("DARK_BLUE", &w_color::py_DARK_BLUE, "DARK_BLUE")
            .def("DARK_CYAN", &w_color::py_DARK_CYAN, "DARK_CYAN")
            .def("DARK_GOLDENROD", &w_color::py_DARK_GOLDENROD, "DARK_GOLDENROD")
            .def("DARK_GRAY", &w_color::py_DARK_GRAY, "DARK_GRAY")
            .def("DARK_GREEN", &w_color::py_DARK_GREEN, "DARK_GREEN")
            .def("DARK_KHAKI", &w_color::py_DARK_KHAKI, "DARK_KHAKI")
            .def("DARK_MAGENTA", &w_color::py_DARK_MAGENTA, "DARK_MAGENTA")
            .def("DARK_OLIVE_GREEN", &w_color::py_DARK_OLIVE_GREEN, "DARK_OLIVE_GREEN")
            .def("DARK_ORANGE", &w_color::py_DARK_ORANGE, "DARK_ORANGE")
            .def("DARK_ORCHID", &w_color::py_DARK_ORCHID, "DARK_ORCHID")
            .def("DARK_RED", &w_color::py_DARK_RED, "DARK_RED")
            .def("DARK_SALMON", &w_color::py_DARK_SALMON, "DARK_SALMON")
            .def("DARK_SEA_GREEN", &w_color::py_DARK_SEA_GREEN, "DARK_SEA_GREEN")
            .def("DARK_SLATE_BLUE", &w_color::py_DARK_SLATE_BLUE, "DARK_SLATE_BLUE")
            .def("DARK_SLATE_GRAY", &w_color::py_DARK_SLATE_GRAY, "DARK_SLATE_GRAY")
            .def("DARK_TURQUOISE", &w_color::py_DARK_TURQUOISE, "DARK_TURQUOISE")
            .def("DARK_VIOLET", &w_color::py_DARK_VIOLET, "DARK_VIOLET")
            .def("DEEP_PINK", &w_color::py_DEEP_PINK, "DEEP_PINK")
            .def("DEEP_SKY_BLUE", &w_color::py_DEEP_SKY_BLUE, "DEEP_SKY_BLUE")
            .def("DIM_GRAY", &w_color::py_DIM_GRAY, "DIM_GRAY")
            .def("DODGER_BLUE", &w_color::py_DODGER_BLUE, "DODGER_BLUE")
            .def("FIREBRICK", &w_color::py_FIREBRICK, "FIREBRICK")
            .def("FLORAL_WHITE", &w_color::py_FLORAL_WHITE, "FLORAL_WHITE")
            .def("FOREST_GREEN", &w_color::py_FOREST_GREEN, "FOREST_GREEN")
            .def("FUCHSIA", &w_color::py_FUCHSIA, "FUCHSIA")
            .def("GAINSBORO", &w_color::py_GAINSBORO, "GAINSBORO")
            .def("GHOST_WHITE", &w_color::py_GHOST_WHITE, "GHOST_WHITE")
            .def("GOLD", &w_color::py_GOLD, "GOLD")
            .def("GOLDENROD", &w_color::py_GOLDENROD, "GOLDENROD")
            .def("GRAY", &w_color::py_GRAY, "GRAY")
            .def("GREEN", &w_color::py_GREEN, "GREEN")
            .def("GREEN_YELLOW", &w_color::py_GREEN_YELLOW, "GREEN_YELLOW")
            .def("HONEYDEW", &w_color::py_HONEYDEW, "HONEYDEW")
            .def("HOT_PINK", &w_color::py_HOT_PINK, "HOT_PINK")
            .def("INDIAN_RED", &w_color::py_INDIAN_RED, "INDIAN_RED")
            .def("INDIGO", &w_color::py_INDIGO, "INDIGO")
            .def("IVORY", &w_color::py_IVORY, "IVORY")
            .def("KHAKI", &w_color::py_KHAKI, "KHAKI")
            .def("LAVENDER", &w_color::py_LAVENDER, "LAVENDER")
            .def("LAVENDER_BLUSH", &w_color::py_LAVENDER_BLUSH, "LAVENDER_BLUSH")
            .def("LAWN_GREEN", &w_color::py_LAWN_GREEN, "LAWN_GREEN")
            .def("LEMON_CHIFFON", &w_color::py_LEMON_CHIFFON, "LEMON_CHIFFON")
            .def("LIGHT_BLUE", &w_color::py_LIGHT_BLUE, "LIGHT_BLUE")
            .def("LIGHT_CORAL", &w_color::py_LIGHT_CORAL, "LIGHT_CORAL")
            .def("LIGHT_CYAN", &w_color::py_LIGHT_CYAN, "LIGHT_CYAN")
            .def("LIGHT_GOLDENROD_YELLOW", &w_color::py_LIGHT_GOLDENROD_YELLOW, "LIGHT_GOLDENROD_YELLOW")
            .def("LIGHT_GREEN", &w_color::py_LIGHT_GREEN, "LIGHT_GREEN")
            .def("LIGHT_GRAY", &w_color::py_LIGHT_GRAY, "LIGHT_GRAY")
            .def("LIGHT_PINK", &w_color::py_LIGHT_PINK, "LIGHT_PINK")
            .def("LIGHT_SALMON", &w_color::py_LIGHT_SALMON, "LIGHT_SALMON")
            .def("LIGHT_SEA_GREEN", &w_color::py_LIGHT_SEA_GREEN, "LIGHT_SEA_GREEN")
            .def("LIGHT_SKY_BLUE", &w_color::py_LIGHT_SKY_BLUE, "LIGHT_SKY_BLUE")
            .def("LIGHT_SLATE_GRAY", &w_color::py_LIGHT_SLATE_GRAY, "LIGHT_SLATE_GRAY")
            .def("LIGHT_STEEL_BLUE", &w_color::py_LIGHT_STEEL_BLUE, "LIGHT_STEEL_BLUE")
            .def("LIGHT_YELLOW", &w_color::py_LIGHT_YELLOW, "LIGHT_YELLOW")
            .def("LIME", &w_color::py_LIME, "LIME")
            .def("LIME_GREEN", &w_color::py_LIME_GREEN, "LIME_GREEN")
            .def("LINEN", &w_color::py_LINEN, "LINEN")
            .def("MAGENTA", &w_color::py_MAGENTA, "MAGENTA")
            .def("MAROON", &w_color::py_MAROON, "MAROON")
            .def("MEDIUM_AQUAMARINE", &w_color::py_MEDIUM_AQUAMARINE, "MEDIUM_AQUAMARINE")
            .def("MEDIUM_BLUE", &w_color::py_MEDIUM_BLUE, "MEDIUM_BLUE")
            .def("MEDIUM_ORCHID", &w_color::py_MEDIUM_ORCHID, "MEDIUM_ORCHID")
            .def("MEDIUM_PURPLE", &w_color::py_MEDIUM_PURPLE, "MEDIUM_PURPLE")
            .def("MEDIUM_SEA_GREEN", &w_color::py_MEDIUM_SEA_GREEN, "MEDIUM_SEA_GREEN")
            .def("MEDIUM_SLATE_BLUE", &w_color::py_MEDIUM_SLATE_BLUE, "MEDIUM_SLATE_BLUE")
            .def("MEDIUM_SPRING_GREEN", &w_color::py_MEDIUM_SPRING_GREEN, "MEDIUM_SPRING_GREEN")
            .def("MEDIUM_TURQUOISE", &w_color::py_MEDIUM_TURQUOISE, "MEDIUM_TURQUOISE")
            .def("MEDIUM_VIOLET_RED", &w_color::py_MEDIUM_VIOLET_RED, "MEDIUM_VIOLET_RED")
            .def("MIDNIGHT_BLUE", &w_color::py_MIDNIGHT_BLUE, "MIDNIGHT_BLUE")
            .def("MINT_CREAM", &w_color::py_MINT_CREAM, "MINT_CREAM")
            .def("MISTY_ROSE", &w_color::py_MISTY_ROSE, "MISTY_ROSE")
            .def("MOCCASIN", &w_color::py_MOCCASIN, "MOCCASIN")
            .def("NAVAJO_WHITE", &w_color::py_NAVAJO_WHITE, "NAVAJO_WHITE")
            .def("NAVY", &w_color::py_NAVY, "NAVY")
            .def("OLD_LACE", &w_color::py_OLD_LACE, "OLD_LACE")
            .def("OLIVE", &w_color::py_OLIVE, "OLIVE")
            .def("OLIVE_DRAB", &w_color::py_OLIVE_DRAB, "OLIVE_DRAB")
            .def("ORANGE", &w_color::py_ORANGE, "ORANGE")
            .def("ORANGE_RED", &w_color::py_ORANGE_RED, "ORANGE_RED")
            .def("ORCHID", &w_color::py_ORCHID, "ORCHID")
            .def("PALE_GOLDENROD", &w_color::py_PALE_GOLDENROD, "PALE_GOLDENROD")
            .def("PALE_GREEN", &w_color::py_PALE_GREEN, "PALE_GREEN")
            .def("PALE_TURQUOISE", &w_color::py_PALE_TURQUOISE, "PALE_TURQUOISE")
            .def("PALE_VIOLET_RED", &w_color::py_PALE_VIOLET_RED, "PALE_VIOLET_RED")
            .def("PAPAYA_WHIP", &w_color::py_PAPAYA_WHIP, "PAPAYA_WHIP")
            .def("PEACH_PUFF", &w_color::py_PEACH_PUFF, "PEACH_PUFF")
            .def("PERU", &w_color::py_PERU, "PERU")
            .def("PINK", &w_color::py_PINK, "PINK")
            .def("PLUM", &w_color::py_PLUM, "PLUM")
            .def("POWDER_BLUE", &w_color::py_POWDER_BLUE, "POWDER_BLUE")
            .def("PURPLE", &w_color::py_PURPLE, "PURPLE")
            .def("RED", &w_color::py_RED, "RED")
            .def("ROSY_BROWN", &w_color::py_ROSY_BROWN, "ROSY_BROWN")
            .def("ROYAL_BLUE", &w_color::py_ROYAL_BLUE, "ROYAL_BLUE")
            .def("SADDLE_BROWN", &w_color::py_SADDLE_BROWN, "SADDLE_BROWN")
            .def("SALMON", &w_color::py_SALMON, "SALMON")
            .def("SANDY_BROWN", &w_color::py_SANDY_BROWN, "SANDY_BROWN")
            .def("SEA_GREEN", &w_color::py_SEA_GREEN, "SEA_GREEN")
            .def("SEA_SHELL", &w_color::py_SEA_SHELL, "SEA_SHELL")
            .def("SIENNA", &w_color::py_SIENNA, "SIENNA")
            .def("SILVER", &w_color::py_SILVER, "SILVER")
            .def("SKY_BLUE", &w_color::py_SKY_BLUE, "SKY_BLUE")
            .def("SLATE_BLUE", &w_color::py_SLATE_BLUE, "SLATE_BLUE")
            .def("SLATE_GRAY", &w_color::py_SLATE_GRAY, "SLATE_GRAY")
            .def("SNOW", &w_color::py_SNOW, "SNOW")
            .def("SPRING_GREEN", &w_color::py_SPRING_GREEN, "SPRING_GREEN")
            .def("STEEL_BLUE", &w_color::py_STEEL_BLUE, "STEEL_BLUE")
            .def("TAN", &w_color::py_TAN, "TAN")
            .def("TEAL", &w_color::py_TEAL, "TEAL")
            .def("THISTLE", &w_color::py_THISTLE, "THISTLE")
            .def("TOMATO", &w_color::py_TOMATO, "TOMATO")
            .def("TRANSPARENT_", &w_color::py_TRANSPARENT_, "TRANSPARENT_")
            .def("TURQUOISE", &w_color::py_TURQUOISE, "TURQUOISE")
            .def("VIOLET", &w_color::py_VIOLET, "VIOLET")
            .def("WHEAT", &w_color::py_WHEAT, "WHEAT")
            .def("WHITE", &w_color::py_WHITE, "WHITE")
            .def("WHITE_SMOKE", &w_color::py_WHITE_SMOKE, "WHITE_SMOKE")
            .def("YELLOW", &w_color::py_YELLOW, "YELLOW")
            .def("YELLOW_GREEN", &w_color::py_YELLOW_GREEN, "YELLOW_GREEN")
        ;
    }
}

#endif//__W_COLOR_PY_H__

#endif //__PYTHON__