/* automatically generated by rust-bindgen 0.59.2 */

pub type __darwin_size_t = ::std::os::raw::c_ulong;
pub type size_t = __darwin_size_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct w_buf_t {
    pub data: *mut u8,
    pub len: size_t,
}
pub type w_buf = *mut w_buf_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct w_rist_t {
    _unused: [u8; 0],
}
pub type w_rist = *mut w_rist_t;
pub const w_rist_mode_w_rist_mode_receiver: w_rist_mode = 0;
pub const w_rist_mode_w_rist_mode_sender: w_rist_mode = 1;
pub type w_rist_mode = ::std::os::raw::c_uint;
extern "C" {
    #[doc = " initialize rist"]
    #[doc = " @param p_rist the object of rist"]
    #[doc = " @param p_mode the sender or receiver modes"]
    #[doc = " @param p_profile the profile of rist"]
    #[doc = " @param p_url the url"]
    #[doc = " @param p_loss_percent the loss percent an int value between 0 to 100"]
    #[doc = " @param p_trace the trace information in the string format with maximum size of 256"]
    #[doc = " @return 0 on success, 1 on invalid parameter and -1 on error which the error description will be printed into p_trace"]
    pub fn w_rist_init(
        p_rist: *mut w_rist,
        p_mode: w_rist_mode,
        p_profile: ::std::os::raw::c_int,
        p_url: *const ::std::os::raw::c_char,
        p_loss_percent: ::std::os::raw::c_int,
        p_trace: w_buf,
    ) -> ::std::os::raw::c_int;
}
