/*
	Project			 : Wolf Engine. Copyright (c) Pooya Eimandar All rights reserved. https://github.com/PooyaEimandar/Wolf-Engine
	File Name        : pch.h
	File Description : pre-compiled header of Maya Plugin
	Generated by     : Pooya Eimandar on Oct 3, 2014
	Last modified by : Pooya Eimandar on Oct 3, 2014
	Comment          :
*/

#pragma once

#pragma comment(lib, "OpenMayaRender.lib")
#pragma comment(lib, "OpenMaya.lib")
#pragma comment(lib, "OpenMayaUI.lib")
#pragma comment(lib, "Foundation.lib")


#include <maya/MGlobal.h>
#include <maya/MObject.h>
#include <maya/MMatrix.h>
#include <maya/MString.h>
#include <maya/MStringArray.h>
#include <maya/MDagPath.h>
#include <maya/MObjectHandle.h>
#include <maya/MFnPlugin.h>
#include <maya/MSceneMessage.h>
#include <maya/MRenderingInfo.h>
#include <maya/MRenderTarget.h>
#include <maya/MItDependencyNodes.h>
#include <maya/MMessage.h> // For monitoring geometry list nodes
#include <maya/MFnMesh.h>
#include <maya/MPointArray.h>

#include <Logger.h>
#include <IO.h>

namespace Wolf
{
	enum WCommnads : byte { NOP = 0, LoadScene };
	extern WCommnads Commands;
}