/*
	Project			 : Wolf Engine. Copyright (c) Pooya Eimandar All rights reserved. https://github.com/PooyaEimandar/WolfEngine
	File Name        : MayaViewportRenderer.h
	File Description : Renderer of maya viewport 
	Generated by     : Pooya Eimandar on Oct 3, 2014
	Last modified by : Pooya Eimandar on Oct 3, 2014
	Comment          :
*/

#pragma once

#include <maya/MViewportRenderer.h>
#include <maya/MRenderTarget.h>
#include <maya/MImage.h>
#include <Game.h>

class WolfViewportRenderer : public MViewportRenderer
{
public:
	WolfViewportRenderer();
	virtual ~WolfViewportRenderer();

	// Required virtual overrides from MViewportRenderer
	virtual	MStatus				initialize();
	virtual	MStatus				uninitialize();
	virtual MStatus				render(const MRenderingInfo &renderInfo);
	virtual bool				nativelySupports(MViewportRenderer::RenderingAPI api, float version);
	virtual bool				override(MViewportRenderer::RenderingOverride override);

	virtual unsigned int		overrideThenStandardExclusion() const;

	void*						Command();

protected:
	RenderingAPI											mayaAPI;		
	float													mayaVersion;	
	HWND													mayaHwnd;
	std::unique_ptr<Game>									game;

private:
	void CheckCommands();
	void LoadMayaScene();

	WNDCLASSEX												winClass;
	BYTE*													renderPixels;
	MImage													mayaBackBuffer;
};


