/* automatically generated by rust-bindgen 0.60.1 */

pub const _VCRT_COMPILER_PREPROCESSOR: u32 = 1;
pub const _SAL_VERSION: u32 = 20;
pub const __SAL_H_VERSION: u32 = 180000000;
pub const _USE_DECLSPECS_FOR_SAL: u32 = 0;
pub const _USE_ATTRIBUTES_FOR_SAL: u32 = 0;
pub const _CRT_PACKING: u32 = 8;
pub const _HAS_EXCEPTIONS: u32 = 1;
pub const _STL_LANG: u32 = 0;
pub const _HAS_CXX17: u32 = 0;
pub const _HAS_CXX20: u32 = 0;
pub const _HAS_CXX23: u32 = 0;
pub const _HAS_NODISCARD: u32 = 0;
pub const _ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE: u32 = 1;
pub const _CRT_BUILD_DESKTOP_APP: u32 = 1;
pub const _ARGMAX: u32 = 100;
pub const _CRT_INT_MAX: u32 = 2147483647;
pub const _CRT_FUNCTIONS_REQUIRED: u32 = 1;
pub const _CRT_HAS_CXX17: u32 = 0;
pub const _CRT_HAS_C11: u32 = 1;
pub const _CRT_INTERNAL_NONSTDC_NAMES: u32 = 1;
pub const __STDC_SECURE_LIB__: u32 = 200411;
pub const __GOT_SECURE_LIB__: u32 = 200411;
pub const __STDC_WANT_SECURE_LIB__: u32 = 1;
pub const _SECURECRT_FILL_BUFFER_PATTERN: u32 = 254;
pub const _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES: u32 = 0;
pub const _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_COUNT: u32 = 0;
pub const _CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES: u32 = 1;
pub const _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_MEMORY: u32 = 0;
pub const _CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES_MEMORY: u32 = 0;
pub const WCHAR_MIN: u32 = 0;
pub const WCHAR_MAX: u32 = 65535;
pub const WINT_MIN: u32 = 0;
pub const WINT_MAX: u32 = 65535;
pub const W_MAX_PATH: u32 = 260;
pub type va_list = *mut ::std::os::raw::c_char;
extern "C" {
    pub fn __va_start(arg1: *mut *mut ::std::os::raw::c_char, ...);
}
pub type size_t = ::std::os::raw::c_ulonglong;
pub type __vcrt_bool = bool;
pub type wchar_t = ::std::os::raw::c_ushort;
extern "C" {
    pub fn __security_init_cookie();
}
extern "C" {
    pub fn __security_check_cookie(_StackCookie: usize);
}
extern "C" {
    pub fn __report_gsfailure(_StackCookie: usize);
}
extern "C" {
    pub static mut __security_cookie: usize;
}
pub type __crt_bool = bool;
extern "C" {
    pub fn _invalid_parameter_noinfo();
}
extern "C" {
    pub fn _invalid_parameter_noinfo_noreturn();
}
extern "C" {
    pub fn _invoke_watson(
        _Expression: *const wchar_t,
        _FunctionName: *const wchar_t,
        _FileName: *const wchar_t,
        _LineNo: ::std::os::raw::c_uint,
        _Reserved: usize,
    );
}
pub type errno_t = ::std::os::raw::c_int;
pub type wint_t = ::std::os::raw::c_ushort;
pub type wctype_t = ::std::os::raw::c_ushort;
pub type __time32_t = ::std::os::raw::c_long;
pub type __time64_t = ::std::os::raw::c_longlong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __crt_locale_data_public {
    pub _locale_pctype: *const ::std::os::raw::c_ushort,
    pub _locale_mb_cur_max: ::std::os::raw::c_int,
    pub _locale_lc_codepage: ::std::os::raw::c_uint,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __crt_locale_pointers {
    pub locinfo: *mut __crt_locale_data,
    pub mbcinfo: *mut __crt_multibyte_data,
}
pub type _locale_t = *mut __crt_locale_pointers;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Mbstatet {
    pub _Wchar: ::std::os::raw::c_ulong,
    pub _Byte: ::std::os::raw::c_ushort,
    pub _State: ::std::os::raw::c_ushort,
}
pub type mbstate_t = _Mbstatet;
pub type time_t = __time64_t;
pub type rsize_t = size_t;
extern "C" {
    pub fn _errno() -> *mut ::std::os::raw::c_int;
}
extern "C" {
    pub fn _set_errno(_Value: ::std::os::raw::c_int) -> errno_t;
}
extern "C" {
    pub fn _get_errno(_Value: *mut ::std::os::raw::c_int) -> errno_t;
}
extern "C" {
    pub fn __threadid() -> ::std::os::raw::c_ulong;
}
extern "C" {
    pub fn __threadhandle() -> usize;
}
pub type int_least8_t = ::std::os::raw::c_schar;
pub type int_least16_t = ::std::os::raw::c_short;
pub type int_least32_t = ::std::os::raw::c_int;
pub type int_least64_t = ::std::os::raw::c_longlong;
pub type uint_least8_t = ::std::os::raw::c_uchar;
pub type uint_least16_t = ::std::os::raw::c_ushort;
pub type uint_least32_t = ::std::os::raw::c_uint;
pub type uint_least64_t = ::std::os::raw::c_ulonglong;
pub type int_fast8_t = ::std::os::raw::c_schar;
pub type int_fast16_t = ::std::os::raw::c_int;
pub type int_fast32_t = ::std::os::raw::c_int;
pub type int_fast64_t = ::std::os::raw::c_longlong;
pub type uint_fast8_t = ::std::os::raw::c_uchar;
pub type uint_fast16_t = ::std::os::raw::c_uint;
pub type uint_fast32_t = ::std::os::raw::c_uint;
pub type uint_fast64_t = ::std::os::raw::c_ulonglong;
pub type intmax_t = ::std::os::raw::c_longlong;
pub type uintmax_t = ::std::os::raw::c_ulonglong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rist_data_block {
    _unused: [u8; 0],
}
pub type w_rist_data_block = *mut rist_data_block;
extern "C" {
    pub fn w_rist_init_data_block(p_block: *mut w_rist_data_block) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn w_rist_set_data_block(
        p_block: w_rist_data_block,
        p_data: *const ::std::os::raw::c_void,
        p_data_len: size_t,
    );
}
extern "C" {
    pub fn w_rist_get_data_block(p_block: w_rist_data_block) -> *const ::std::os::raw::c_void;
}
extern "C" {
    pub fn w_rist_get_data_block_len(p_block: w_rist_data_block) -> size_t;
}
extern "C" {
    pub fn w_rist_free_data_block(p_block: *mut w_rist_data_block);
}
pub type rist_log_level = ::std::os::raw::c_int;
pub type rist_ctx_mode = ::std::os::raw::c_int;
pub type rist_profile = ::std::os::raw::c_int;
pub type rist_connection_status = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rist_peer {
    _unused: [u8; 0],
}
pub type w_rist_peer = *mut rist_peer;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rist_oob_block {
    _unused: [u8; 0],
}
pub type w_rist_oob_block = *const rist_oob_block;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rist_stats {
    _unused: [u8; 0],
}
pub type w_rist_stats = *const rist_stats;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct w_rist_ctx_t {
    _unused: [u8; 0],
}
pub type w_rist_ctx = *mut w_rist_ctx_t;
pub type w_rist_log_callback = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut ::std::os::raw::c_void,
        arg2: rist_log_level,
        arg3: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int,
>;
pub type w_rist_auth_connect_callback = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut ::std::os::raw::c_void,
        arg2: *const ::std::os::raw::c_char,
        arg3: u16,
        arg4: *const ::std::os::raw::c_char,
        arg5: u16,
        arg6: w_rist_peer,
    ) -> ::std::os::raw::c_int,
>;
pub type w_rist_auth_disconnect_callback = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut ::std::os::raw::c_void,
        arg2: w_rist_peer,
    ) -> ::std::os::raw::c_int,
>;
pub type w_rist_connection_status_callback = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut ::std::os::raw::c_void,
        arg2: w_rist_peer,
        arg3: rist_connection_status,
    ),
>;
pub type w_rist_out_of_band_callback = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut ::std::os::raw::c_void,
        arg2: w_rist_oob_block,
    ) -> ::std::os::raw::c_int,
>;
pub type w_rist_stats_callback = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut ::std::os::raw::c_void,
        arg2: w_rist_stats,
    ) -> ::std::os::raw::c_int,
>;
pub type w_receiver_data_callback = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut ::std::os::raw::c_void,
        arg2: w_rist_data_block,
    ) -> ::std::os::raw::c_int,
>;
extern "C" {
    pub fn w_rist_init(
        p_rist: *mut w_rist_ctx,
        p_mode: rist_ctx_mode,
        p_profile: rist_profile,
        p_loss_percentage: u16,
        p_log_level: rist_log_level,
        p_log_callback: w_rist_log_callback,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn w_rist_connect(
        p_rist: w_rist_ctx,
        p_url: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn w_rist_set_auth_handler(
        p_rist: w_rist_ctx,
        p_arg: *mut ::std::os::raw::c_void,
        p_on_auth_connect_cb: w_rist_auth_connect_callback,
        p_on_auth_disconnect_cb: w_rist_auth_disconnect_callback,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn w_rist_set_conn_status_callback(
        p_rist: w_rist_ctx,
        p_arg: *mut ::std::os::raw::c_void,
        p_on_connect_status_cb: w_rist_connection_status_callback,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn w_rist_set_out_of_band_callback(
        p_rist: w_rist_ctx,
        p_arg: *mut ::std::os::raw::c_void,
        p_on_out_of_band_cb: w_rist_out_of_band_callback,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn w_rist_set_stats_callback(
        p_rist: w_rist_ctx,
        p_interval: ::std::os::raw::c_int,
        p_arg: *mut ::std::os::raw::c_void,
        p_on_stats_cb: w_rist_stats_callback,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn w_rist_write(p_rist: w_rist_ctx, p_block: w_rist_data_block) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn w_rist_read(
        p_rist: w_rist_ctx,
        p_block: *mut w_rist_data_block,
        p_timeout: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn w_rist_set_receiver_data_callback(
        p_rist: w_rist_ctx,
        p_on_receive_cb: w_receiver_data_callback,
        p_arg: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn w_rist_fini(p_rist: *mut w_rist_ctx);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __crt_locale_data {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __crt_multibyte_data {
    pub _address: u8,
}
